#version: "3.7"
#services:
#  api_service:
#    build: .
#    restart: always
#    ports:
#      - 8888:8888
#    networks:
#      - springapimysql-net
#    environment:
#      - spring.datasource.url=jdbc:mysql://mysqldb:3306/MService?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true
#    depends_on:
#      - mysqldb
#    volumes:
#      - .m2:/root/.m2
#
#  mysqldb:
#    image: "mysql:8.0"
#    restart: always
#    ports:
#      - 3308:3306
#    networks:
#      - springapimysql-net
#    environment:
#      MYSQL_DATABASE: MService
#      MYSQL_PASSWORD:
#      MYSQL_ROOT_PASSWORD:
#      MYSQL_ALLOW_EMPTY_PASSWORD: "true"
#networks:
#  springapimysql-net: